name: workflow 1
on: push


jobs:
    echo: 
        needs: show_README
        runs-on: ubuntu-latest
        steps:
            - name: Welcome 
              run: |
                echo "Hello world"
            
            - name: checkout code
              uses: actions/checkout@v4
                
            - name: Install cowsay
              run: |
                sudo apt update -y
                sudo apt install cowsay -y
                cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
                cat dragon.txt
            
    show_README:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Run a script
              run: |
                    chmod +x .github/workflows/script.sh
                    ./.github/workflows/script.sh